- name:        Files   /etc/systemd/system
  become_user:  root
  become:       yes
  template:  src="etc/systemd/system/pg-CLUSTER.service"  dest="/etc/systemd/system/pg-{{cluster}}.service"   owner=root mode=644 

########## ensure symlink ~/postgres/dist-{{ cluster }}
- name: ensure symlink "dist-{{cluster}}"
  file: src="{{ HOME }}/postgres/pg-{{ postgres_REL }}"  dest="{{ HOME }}/postgres/dist-{{cluster}}"  state=link owner=postgres group=postgres


#############################################
- name:             start systemd
  become_user:      root
  become:           yes
  systemd:    
     name:          "pg-{{ cluster }}"
     daemon_reload: yes    
     state:         started   
     enabled:       no
     force:         yes
