- name:        Files   /etc/systemd/system
  become_user:  root
  become:       yes
  template:  src="etc/systemd/system/pg-CLUSTER.service"  dest="/etc/systemd/system/pg-{{cluster}}.service"   owner=root mode=644 

- name:             start systemd
  when:             false
  systemd:    
     name:          "pg-{{ cluster }}"
     daemon_reload: yes    
     state:         started   
     enabled:       yes 
     force:         yes
